language: java
jdk:
  - openjdk11

services:
  - docker

script:
  - ./mvnw clean install -B -Dspring.data.mongodb.uri=${MONGO_URL}

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master