language: java
jdk:
  - openjdk11

services:
  - docker

install: true

script:
  - docker build -t abhithube/member-details .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master